[package]
name = "wunix-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {workspace=true}
anyhow = {workspace=true}
file-format = "0.24.0"
